# ━ Bot Values ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
bot_status: idle
bot_activity: "Grimwald Season 19!"
sudo_prefix: "o/ "
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ━ IDs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
sudo_users:
    - 1027380375028244551 # roc.py
    - 590556755046694922 # bennyboy12306
home_server: 755056745717432350 # grimwald - ofc
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ━ Colors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
colors:
    primary: 0xE86B11
    secondary: 0x0F0C0A
    invisible: 0x2B2D31
    success: 0x00D355
    error: 0xDF0043
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ━ Emojis ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
emojis:
    network: <:network:1257924179056132116>
    enabled: <:enabled:1257924178095378442>
    disabled: <:disabled:1257924176799600690>
    bullet: <:bullet:1257924175125942364>
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ━ Blacklists ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
blacklists:
    autoresponse_channels:
        - 849310724844027941 # discord-to-minecraft
